name: Build the app


on:
  watch:
    types: [started]



jobs:
  build:
    name: Build the app
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log to tg
      env:
        chat_id: ${{ secrets.CHAT_ID }}
        bot_token: ${{ secrets.TG_TOKEN }}
      run: |
        curl -d chat_id=${chat_id} -d text="Compile Routine Created..." https://api.telegram.org/bot${bot_token}/sendMessage

    - name: Clone the git
      run: git clone https://github.com/Chainfire/libsuperuser

    - name: Update package list
      run: sudo apt update && sudo apt upgrade -y

    - name: Install gradle
      run: sudo apt install gradle

    - name: Build
      run: (cd libsuperuser/libsuperuser_example/; gradle assemble)

    - name: Log to tg
      env:
        chat_id: ${{ secrets.CHAT_ID }}
        bot_token: ${{ secrets.TG_TOKEN }}
      run: |
        curl -d chat_id=${chat_id} -d text="Build has Started..." https://api.telegram.org/bot${bot_token}/sendMessage

    - uses: actions/upload-artifact@v2
      with:
        name: Upload Artifact
        path: ./libsuperuser/libsuperuser_example/


    - name: Notification Build Complete
      env:
        chat_id: ${{ secrets.CHAT_ID }}
        bot_token: ${{ secrets.TG_TOKEN }}
      run: curl -d chat_id=${chat_id} -d text="Compile Complete. Check \n https://github.com/CypherpunkArmoury/Compiled" https://api.telegram.org/bot${bot_token}/sendMessage

